version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SlackEventApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r7h19wei3tuz"
s3_prefix = "SlackEventApp"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
