AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  slack-event-app
 
Parameters:
  StageName:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Default: dev

Resources:
  SlackEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: slackEventHandlerFunction
      Handler: src/handlers/eventHandler.lambdaHandler
      AutoPublishAlias: !Ref StageName
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - LambdaInvokePolicy:
            FunctionName: slackBlockMessageFunction
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: "Add Secret"
          SLACK_BOT_TOKEN: "Add Secret"
      Events:
        SlackEventAPI:
          Type: Api
          Properties:
            Path: /rockets
            Method: post

  SlackBlockMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: slackBlockMessageFunction
      Handler: src/handlers/blockMessageHandler.lambdaHandler
      AutoPublishAlias: !Ref StageName
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: "Add Secret"
          SLACK_BOT_TOKEN: "Add Secret"
